# -*- coding: utf-8 -*-
# Copyright: 2018-present Samsung Electronics Co., Ltd. and other contributors

version: "2"

networks:
  castanets-net:
  
services:

  version:
    image: rzrfreefr/castanets:latest
    command: --version

  browser:
    image: rzrfreefr/castanets:latest
    command: --no-sandbox https://github.com/samsung/castanets
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    networks:
      castanets-net:
        aliases:
         - castanets-host

  renderer:
    image: rzrfreefr/castanets:latest
    command: --no-sandbox --type=renderer --server-address=castanets-host
    networks:
      - castanets-net
