/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "f13f8690bede09ca97071e9786d68bc0758a24cc"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
